
def a():
    raise Exception('some exception')